trigger:
  - develop
  - main
  - uat

resources:
  repositories:
    - repository: AngularTemplate
      type: git
      name: PipeLines/PipeLines
      ref: refs/heads/main

pool:
  name: $(AGENT_POOL_NAME)

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - group: commons-env-dev
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - group: commons-env-prd
  - ${{ if eq(variables['Build.SourceBranchName'], 'qa') }}:
      - group: commons-env-qa


extends:
  template: /Angular/Deploy/build-and-deploy-angular.yml@AngularTemplate
  parameters:
    ENVIRONMENT: $(ENVIRONMENT)
    REPOSITORY_NAME: $(Build.Repository.Name)
    DOCKER_CONNECTION_NAME: $(DOCKER_CONNECTION_NAME)
    ACCESS_TOKEN: $(ACCESS_TOKEN)
    INFRASTRUCTURE_PROJECT: $(INFRASTRUCTURE_PROJECT)
    SONAR_CONNECTION_NAME: $(SONAR_CONNECTION_NAME)
    SONAR_TOKEN: $(SONAR_TOKEN)
    BRANCH_NAME: $(Build.SourceBranchName)

